name: Executar Tarefa Diária

on:
  schedule:
    # Sintaxe: Minuto Hora Dia-do-Mês Mês Dia-da-Semana (UTC)
    - cron: '0 13 * * *'

  # Permite rodar o workflow manualmente no painel do GitHub
  workflow_dispatch:

# Permissões necessárias para que o bot do GitHub Actions possa salvar (push) no repositório
permissions:
  contents: write

jobs:
  executar-script:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Baixar arquivo CSV do Tesouro Direto
        run: |
          echo "Iniciando o download dos dados do Tesouro Direto..."
          URL="https://www.tesourotransparente.gov.br/ckan/dataset/df56aa42-484a-4a59-8184-7676580c81e3/resource/796d2059-14e9-44e3-80c9-2d9e30b405c1/download/precotaxatesourodireto.csv"
          curl -L -f "$URL" -o data.csv
          echo "Download concluído com sucesso!"
          chmod 755 process_td_data.sh
          ./process_td_data.sh

      - name: Commitar e salvar arquivo no repositório
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add data.csv *json

          # Evita erro caso os dados do dia ainda não tenham sido atualizados no site do Tesouro
          git commit -m "Automático: Atualizando histórico do Tesouro Direto" || echo "Sem alterações para commitar."

          git push
